name: PushTest

on:
  push:
    branches: [ main ]

jobs:

  test:
      runs-on: ubuntu-latest
      steps:
        # Checkout MASTER
        - uses: actions/checkout@v2

        - run: cat README.md

        - run: find        
        
        - run: pwd

        - run: ls ..

        # Checkout LOG
        - uses: actions/checkout@v2
          with:
            repository: pafmon/test-gha-log
            path: log

        - run: ls -l log
        
        - name: Generate Perses Test Project Id
          uses: actions/github-script@v3
          id: generate-project-id
          with:
            script: return (new Date()).toISOString().replace(/(T|:|\.)/g,'-').slice(0,-1)
            result-encoding: string
          
        - name: Check Perses Test Project Id
          run: echo "Perses Test Project ID <${{steps.generate-project-id.outputs.result}}>"  

        - name: Check Perses Test Project Id
          run: echo "Perses Test Project ID <${{steps.generate-project-id.outputs.result}}>" >> log/executions  
        
        - name: Commit files
          run: |
            cd log
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Add changes" -a      

        - name: Push changes
          uses: ad-m/github-push-action@master
        
        